---
- name: List VRRP groups
  hosts: adc_servers
  gather_facts: no
  vars:
    adc_username: "{{ adc_username }}"
    adc_password: "{{ adc_password }}"

    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: List VRRP groups
      adc_system_ha_vrrp:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        vrrp_component: group
        action: list
      register: result

    - name: Display VRRP groups
      debug:
        var: result.groups

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
