---
- name: ldap认证配置
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 ldap认证配置
      adc_system_aaa:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: set_ldap_config
        serverstatus: 1
        hostname: "192.168.100.1"
        ldap_cn: "cn"
        ldap_dn: "ou=Horizon,dc=test,dc=com"
        ldap_timeout: 3
        ldap_port: 389
        ldap_ssl: 0
        serverstatus2: 0
        hostname2: "192.168.200.1"
        ldap_cn2: "cn"
        ldap_dn2: "ou=Horizon,dc=test,dc=com"
        ldap_timeout2: 3
        ldap_port2: 389
        ldap_ssl2: 0
      register: result
      when: login_result is succeeded

    - name: 显示 ldap认证配置 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
