---
- name: 配置同步pull-push
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 配置同步pull-push
      adc_vrrp_cfgsync_action_pull_push:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: execute
        group: "example_value"
        # 根据实际需求添加更多参数
      register: result
      when: login_result is succeeded

    - name: 显示 配置同步pull-push 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
