---
- name: 被动健康检查编辑
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 编辑被动健康检查
      adc_slb_passive_health_check:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: "passive_health_check_edit"
        name: "test_phc"
        type: "http"
        enable: 1
        phc_action: "reset"
        timeout: 60
        interval: 10
        rise: 5
        fall: 5
      register: result
      when: login_result is succeeded

    - name: 输出结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
