---
- name: 增加静态arp配置
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 增加静态arp配置
      adc_network_arp:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: add_ipv6_entry
        ip_addr: "2001:db8::1"
        mac_addr: "00:11:22:33:44:55"
        port_type: 1  # 1：以太口,3；trunk 口
        slot_num: 0  # 接口插槽号，当指定 port_type 为 1 时需要指定该参数
        port_num: 1  # 接口号，当指定 port_type 为 1 时表示以太网接口号，为 3 时表示 trunk 号
      register: result
      when: login_result is succeeded

    - name: 显示 增加静态arp配置 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
