---
- name: 获取以太网接口详情
  hosts: localhost
  gather_facts: no
  vars:
    ip: "{{ ip }}"
    authkey: "{{ authkey }}"
  tasks:
    - name: 获取以太网接口详情
      adc_interface_ethernet:
        ip: "{{ ip }}"
        authkey: "{{ authkey }}"
        action: get
        slot: 1
        port: 1
      register: result

    - name: 显示结果
      debug:
        var: result