---
- name: 获取以太网接口列表（包含公共接口）
  hosts: localhost
  gather_facts: no
  vars:
    ip: "{{ ip }}"
    authkey: "{{ authkey }}"
  tasks:
    - name: 获取以太网接口列表（包含公共接口）
      adc_interface_ethernet:
        ip: "{{ ip }}"
        authkey: "{{ authkey }}"
        action: list_withcommon
      register: result

    - name: 显示结果
      debug:
        var: result