---
- name: 添加SNMP团体字
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  
  vars:
    community: "public"
    host: "192.168.1.100"
  
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 添加SNMP团体字
      adc_system_snmp:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: "add_community"
        # API action: snmp.comm.item.add
        community: "{{ community }}"
        host: "{{ host }}"
      register: result
      when: login_result is succeeded

    - name: 显示 添加SNMP团体字 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
