---
- name: http hostswitch delete
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 http hostswitch delete
      adc_slb_profile:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "http_hostswitch_del"
        name: "{ hostswitch_profile_name }"
        # API action: slb.profile.http.hostswitch.del
      register: result
      when: login_result is succeeded

    - name: 显示 http hostswitch delete 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined