---
- name: dns模板编辑
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 dns模板编辑
      adc_slb_profile_dns:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "edit_profile"
        # API action: slb.profile.dns.edit
        name: "dns_profile_1"
        description: "更新后的DNS模板描述"
        enabled: 1
        drop_bad_req: 0
        default_to_cache: 0
        cache_size: 500
      register: result
      when: login_result is succeeded

    - name: 显示 dns模板编辑 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
