---
- name: http hostswitch add
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 http hostswitch add
      adc_slb_profile_http_hostswitch:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "http_hostswitch_add"
        # API action: slb.profile.http.hostswitch.add
        name: "profile_http_1"
        # host_class: [
        #   {
        #     "host": "adc",
        #     "pool": "pool_tcp",
        #     "type": 0
        #   },
        #   {
        #     "host": "adc_1",
        #     "pool": "pool_tcp",
        #     "type": 1
        #   },
        #   {
        #     "host": "adc_2",
        #     "pool": "pool_tcp",
        #     "type": 2
        #   }
        # ]
      register: result
      when: login_result is succeeded

    - name: 显示 http hostswitch add 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined