---
- name: 上传WAF规则文件
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  
  vars:
    file_path: "/path/to/waf_rule.rules"
  
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 上传WAF规则文件
      adc_waf_rule:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: "waf_rule_upload"
        # API action: waf.rule.upload
        file_path: "{{ file_path }}"
      register: result
      when: login_result is succeeded

    - name: 显示 上传WAF规则文件 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined