---
- name: postfile upload
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 postfile upload
      adc_slb_healthcheck_postfile:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "healthcheck_postfile_upload"
        # API action: slb.healthcheck.postfile.upload
        name: "postfile_name"  # 上传后的文件名
        file_path: "/path/to/local/file.txt"  # 本地文件路径
      register: result
      when: login_result is succeeded

    - name: 显示 postfile upload 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
