---
- name: request_log list
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 request_log list
      adc_slb_profile:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "request_log_list"
        # API action: slb.profile.request_log.list
        # TODO: 添加必要的参数
      register: result
      when: login_result is succeeded

    - name: 显示 request_log list 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
