---
- name: allow_promis_intf_vip get
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 allow_promis_intf_vip get
      adc_slb_global:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "allow_promis_intf_vip_get"
        # API action: slb.global.allow_promis_intf_vip.get
        # TODO: 添加必要的参数
      register: result
      when: login_result is succeeded

    - name: 显示 allow_promis_intf_vip get 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
