---
- name: ssl crl upload
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{ inventory_hostname }"
        username: "{ adc_username }"
        password: "{ adc_password }"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 ssl crl upload
      adc_slb_ssl_certificate:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
        action: "crl_upload"
        file_path: "{ ssl_crl_file_path }"
        crl_name: "{ ssl_crl_name }"
        # API action: slb.ssl.crl.upload
      register: result
      when: login_result is succeeded

    - name: 显示 ssl crl upload 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{ inventory_hostname }"
        authkey: "{ login_result.authkey }"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined