---
- name: 获取 SLB 全局源 NAT 接口地址轮询
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 获取 SLB 全局源 NAT 接口地址轮询
      adc_system_global_config:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: "global_slb_snat_interface_iprr_get"
        # API action: global.slb_snat_interface_iprr.get
        # 以下为可选参数
      register: result
      when: login_result is succeeded

    - name: 显示 获取 SLB 全局源 NAT 接口地址轮询 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
