---
- name: list profiles withcommon
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 显示登录结果
      debug:
        var: login_result

    - name: 执行 list profiles withcommon
      adc_slb_profile_http:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: "list_profiles_withcommon"
        # API action: slb.profile.http.list.withcommon
        # 以下为可选参数
      register: result
      when: login_result is succeeded

    - name: 显示 list profiles withcommon 结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
