---
- name: Delete Rule Table
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  vars:
    ruletable_name: "test_ruletable"

  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: Delete rule table
      adc_slb_ruletable:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: delete_ruletable
        name: "{{ ruletable_name }}"
      register: result

    - name: Display result
      debug:
        var: result.result

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
