---
- name: Get Client SSL Profile Details
  hosts: adc_servers
  gather_facts: no
  vars:
    # 添加默认的用户名和密码
    adc_username: "admin"
    adc_password: "admin"
    profile_name: "test_ssl_client_profile"

  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: Get client SSL profile details
      adc_slb_sslclient:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: get_profile
        name: "{{ profile_name }}" # 使用变量而不是直接使用保留关键字
      register: sslclient_result # 更改变量名避免使用保留关键字

    - name: Display client SSL profile details
      debug:
        var: sslclient_result # 使用新的变量名

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
