---
- name: Add Server SSL Profile
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  vars:
    profile_name: "test_ssl_server_profile"
    cert_name: "test_cert"
    key_name: "test_key"
  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: Add server SSL profile
      adc_slb_sslserver:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: add_profile
        name: "{{ profile_name }}"
        cert: "{{ cert_name }}"
        key: "{{ key_name }}"
      register: result

    - name: Display result
      debug:
        var: result.result

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
