---
- name: List WAF Profiles
  hosts: adc_servers
  gather_facts: no
  vars:
    # 添加默认的用户名和密码
    adc_username: "admin"
    adc_password: "admin"

  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: Get list of WAF profiles
      adc_waf_profile:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: list_profiles
      register: waf_result # 更改变量名避免使用保留关键字

    - name: Display WAF profiles
      debug:
        var: waf_result # 使用新的变量名

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
