---
- name: 编辑SMTP配置
  collections:
    - horizon.modules
  hosts: adc_servers
  gather_facts: no
  vars:
    adc_ip: "{{ inventory_hostname }}"
    adc_authkey: "{{ login_result.authkey }}"

  tasks:
    - name: 登录ADC设备
      adc_login:
        ip: "{{ inventory_hostname }}"
        username: "{{ adc_username }}"
        password: "{{ adc_password }}"
      register: login_result

    - name: 编辑SMTP配置
      adc_system_smtp:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
        action: set_smtp_config
        server: "smtp.example.com"
        port: 25
        emailto: "admin@example.com"
        emailfrom: "adc@example.com"
        auth: 1
        user: "smtpuser"
        password: "smtppassword"
      register: result
      when: login_result is succeeded

    - name: 显示编辑结果
      debug:
        var: result
      when: result is defined

    - name: 登出ADC设备
      adc_logout:
        ip: "{{ inventory_hostname }}"
        authkey: "{{ login_result.authkey }}"
      register: logout_result
      when: login_result is succeeded

    - name: 显示登出结果
      debug:
        var: logout_result
      when: logout_result is defined
